[package]
name = "api"
version = "0.1.0"
description = "An example Tauri Application showcasing the api"
edition = "2021"
rust-version = "1.64"
license = "Apache-2.0 OR MIT"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-alpha.4", features = ["codegen", "isolation"] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tiny_http = "0.11"
log = "0.4"
tauri-plugin-log = { path = "../../../plugins/log" }
tauri-plugin-cli = { path = "../../../plugins/cli" }
tauri-plugin-fs = { path = "../../../plugins/fs" }

[patch.crates-io]
tauri = { git = "https://github.com/tauri-apps/tauri", branch = "next" }
tauri-build = { git = "https://github.com/tauri-apps/tauri", branch = "next" }

[dependencies.tauri]
version = "2.0.0-alpha.8"
features = [
  "api-all",
  "global-shortcut",
  "http-multipart",
  "icon-ico",
  "icon-png",
  "isolation",
  "macos-private-api",
  "windows7-compat",
  "system-tray",
  "updater"
]

[target."cfg(target_os = \"windows\")".dependencies]
window-shadows = "0.2"

[features]
custom-protocol = [ "tauri/custom-protocol" ]

# default to small, optimized release binaries
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
